# Generated by Django 2.2.19 on 2022-10-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20221015_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
